import type { ClassType, GymClass } from "@fit-core/shared";

// ─── Class type color map (Tailwind classes — web only) ───────────────────────

export const classTypeColors: Record<
  ClassType,
  {
    bg: string;
    border: string;
    text: string;
    dot: string;
  }
> = {
  Yoga: {
    bg: "bg-purple-50",
    border: "border-purple-200",
    text: "text-purple-700",
    dot: "bg-purple-400",
  },
  HIIT: {
    bg: "bg-orange-50",
    border: "border-orange-200",
    text: "text-orange-700",
    dot: "bg-orange-400",
  },
  Pilates: {
    bg: "bg-teal-50",
    border: "border-teal-200",
    text: "text-teal-700",
    dot: "bg-teal-400",
  },
  Cycling: {
    bg: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-700",
    dot: "bg-blue-400",
  },
  Strength: {
    bg: "bg-ghost",
    border: "border-stroke",
    text: "text-primary",
    dot: "bg-navy",
  },
};

// ─── Dummy data ───────────────────────────────────────────────────────────────

export const weekClasses: GymClass[] = [
  {
    id: "1",
    name: "Morning HIIT",
    type: "HIIT",
    trainer: "James Carter",
    day: "Mon",
    startTime: "07:00",
    duration: 45,
    booked: 12,
    capacity: 12,
  },
  {
    id: "2",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:15",
    duration: 90,
    booked: 8,
    capacity: 15,
  },
  {
    id: "25",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:15",
    duration: 90,
    booked: 8,
    capacity: 15,
  },
  {
    id: "22",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:15",
    duration: 90,
    booked: 8,
    capacity: 15,
  },
  {
    id: "2",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:15",
    duration: 90,
    booked: 8,
    capacity: 15,
  },
  {
    id: "2",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:00",
    duration: 50,
    booked: 8,
    capacity: 15,
  },
  {
    id: "2",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:00",
    duration: 50,
    booked: 8,
    capacity: 15,
  },
  {
    id: "2",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:00",
    duration: 50,
    booked: 8,
    capacity: 15,
  },
  {
    id: "2",
    name: "Yoga Flow",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Mon",
    startTime: "09:15",
    duration: 90,
    booked: 8,
    capacity: 15,
  },
  {
    id: "3",
    name: "Spin Class",
    type: "Cycling",
    trainer: "Coach Ben",
    day: "Tue",
    startTime: "10:00",
    duration: 45,
    booked: 10,
    capacity: 12,
  },
  {
    id: "4",
    name: "Pilates Core",
    type: "Pilates",
    trainer: "Coach Maria",
    day: "Tue",
    startTime: "10:00",
    duration: 50,
    booked: 6,
    capacity: 10,
  },
  {
    id: "5",
    name: "Strength & Conditioning",
    type: "Strength",
    trainer: "James Carter",
    day: "Wed",
    startTime: "06:00",
    duration: 75,
    booked: 9,
    capacity: 12,
  },
  {
    id: "6",
    name: "Evening HIIT",
    type: "HIIT",
    trainer: "Coach Ben",
    day: "Wed",
    startTime: "18:00",
    duration: 45,
    booked: 11,
    capacity: 12,
  },
  {
    id: "7",
    name: "Morning Yoga",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Thu",
    startTime: "08:00",
    duration: 60,
    booked: 7,
    capacity: 15,
  },
  {
    id: "8",
    name: "Cycling Blast",
    type: "Cycling",
    trainer: "Coach Ben",
    day: "Thu",
    startTime: "17:00",
    duration: 45,
    booked: 12,
    capacity: 12,
  },
  {
    id: "9",
    name: "Full Body Strength",
    type: "Strength",
    trainer: "James Carter",
    day: "Fri",
    startTime: "07:00",
    duration: 60,
    booked: 8,
    capacity: 12,
  },
  {
    id: "10",
    name: "Pilates Stretch",
    type: "Pilates",
    trainer: "Coach Maria",
    day: "Fri",
    startTime: "10:00",
    duration: 50,
    booked: 5,
    capacity: 10,
  },
  {
    id: "11",
    name: "Weekend HIIT",
    type: "HIIT",
    trainer: "James Carter",
    day: "Sat",
    startTime: "09:00",
    duration: 45,
    booked: 10,
    capacity: 12,
  },
  {
    id: "12",
    name: "Sunday Yoga",
    type: "Yoga",
    trainer: "Coach Maria",
    day: "Sun",
    startTime: "10:00",
    duration: 60,
    booked: 4,
    capacity: 15,
  },
];
